version: "2"

services:
  go-live:
    image: go-shop-pay
    restart: always
    environment:
      - ADDR=:3000
      - MYSQL_DSN=root:Xr111900@tcp(rm-wz9p9wn6719qplwioho.mysql.rds.aliyuncs.com:3306)/weishandb?charset=utf8&parseTime=true
      - CORS_DOMAIN=*
      - REDIS_ADDR=127.0.0.1:6379
      - REDIS_PASSWORD=
      - MCH_KEY=wA2erDMbqCLw0Fc7
      - MCH_ID=1525105651
      - PAY_CALLBACK=http://fafdfasfdf.natapp1.cc/api/v1/order/update
      - FINISH_CALLBACK=http://fafdfasfdf.natapp1.cc/api/v1/order/put
      - CHECK_CALLBACK=http://fafdfasfdf.natapp1.cc/api/v1/order/check
      - APP_MAP=nil
      - APP_CALLBACK_PAGE=
      - FEE_RATE=0.2
      - WEIXIN_NOTIFY_USERKEY="orPQ806v1hj9l2V8NMhDJM7VXD_0vsJlGlKdoG"
      - GIN_MODE=release
    ports:
      - 3000:80